### ISSUE TITLE
UnboundLocalError: local variable 'forms' referenced before assignment

### ISSUE THREAD

**Issue by GmGniap** [pvernier/pykobo#4]
I'm using `pykobo` in Google Colab. When I try to get form individually, it's showing errors like this.
<img width="792" alt="image" src="https://user-images.githubusercontent.com/20846286/208865486-5095fc9c-e548-4e22-be5c-7f56da7d32f4.png">

**Comment by pvernier** [comment]
Thanks for reporting this bug.
It should be fixed with the release of version [0.1.2](https://github.com/pvernier/pykobo/releases/tag/v0.1.2).
It seemed to happen when calling the method `get_forms` and then `get_form`.
