### ISSUE TITLE
field["name"] not found error

### ISSUE THREAD

**Issue by GmGniap** [pvernier/pykobo#5]
This issue might be because of different Kobotoolbox form structure. In my case, when I tried `fetch_data()` function and the error happened like this: 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/20846286/208867580-34af0ab8-c5d7-42cc-b429-466c0e95521f.png">

When I tried to test `pykobo` locally , I changed `name_q` variable from `form.py`.  As the screenshot below , after I changed `name_q = field["$autoname"]` , the error is being solved. I think it's because they didn't have "name" attribute in some fields, but there's same value "$autoname" that Kobotoolbox automatically generated. We should use that attribute instead of "name".

![image](https://user-images.githubusercontent.com/20846286/208868468-02e339b3-4592-4ce6-8674-c3147434c54e.png)

This issue is also related to this [previous issue](https://github.com/pvernier/pykobo/issues/4) that I opened.

**Working Environments**
Errors happened on Google Colab.
Local code tested on MacOS.

**Comment by pvernier** [comment]
Could you share the XLSForm of your survey  with me (pvernier82@gmail.com)? I'm not sure it's possible for a form to have fields without name. I would expect Kobo to do not allow uploading such a form.

**Comment by lagrandecode** [comment]
Good day @pvernier. I'm trying to use your package but when i get to form.fetch_data(), this is the result 
![image](https://user-images.githubusercontent.com/58033364/212532164-26df8ee2-10c6-472e-809c-b288c7363f01.png)
Please what is the problem? I'm using humanitarianinfo

**Comment by pvernier** [comment]
Thanks @lagrandecode for reporting this issue. Can you send me (at pvernier82@gmail.com) your XLSFrom file? It would make it easier to debug.

**Comment by lagrandecode** [comment]
ok

**Comment by deweatherman** [comment]
Hi @pvernier very nice idea creating this interface! I have the same issue that the others have raised:

Have you tried @GmGniap 's suggestion?

![bugPyKobo](https://user-images.githubusercontent.com/62936516/225070054-11b057e3-4f91-43e5-a706-834431233d0d.png)

**Comment by pvernier** [comment]
Hi @deweatherman,

I just published a new release to address this issue: https://github.com/pvernier/pykobo/releases/tag/v0.1.5

Let me know if it fixes your issue.

**Comment by deweatherman** [comment]
Hi @pvernier , it does! 
This is great! Thanks for the quick answer!
